#ifndef OPENFLIGHTCOMPUTER_BOARD_METADATA_H
#define OPENFLIGHTCOMPUTER_BOARD_METADATA_H

#define OPENFLIGHTCOMPUTER_BOARD_ID "flightcomputer-v1"
#define OPENFLIGHTCOMPUTER_BOARD_NAME "Flight Computer V1"
#define OPENFLIGHTCOMPUTER_BOARD_REVISION "1.7"
#define OPENFLIGHTCOMPUTER_MCU_MODEL "STM32F405RGT6"

#endif
